---
services:
  db:
    image: "postgres:17.4-alpine"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${MT_SKIN_SERVER_DB_USER}
      - POSTGRES_PASSWORD=${MT_SKIN_SERVER_DB_PASSWORD}
      - POSTGRES_DB=${MT_SKIN_SERVER_DB_NAME}
      - DATABASE_HOST=${MT_SKIN_SERVER_DB_HOST}
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data

  server:
    build:
      dockerfile: Dockerfile
      target: development
    environment:
      - MT_SKIN_SERVER_DB_USER=${MT_SKIN_SERVER_DB_USER}
      - MT_SKIN_SERVER_DB_PASSWORD=${MT_SKIN_SERVER_DB_PASSWORD}
      - MT_SKIN_SERVER_DB_NAME=${MT_SKIN_SERVER_DB_NAME}
      - MT_SKIN_SERVER_DB_HOST=${MT_SKIN_SERVER_DB_HOST}
      - MT_SKIN_SERVER_DB_PORT=${MT_SKIN_SERVER_DB_PORT}
      - MT_SKIN_SERVER_DATABASE_LOGGING=${MT_SKIN_SERVER_DATABASE_LOGGING}
      - MT_SKIN_SERVER_OAUTH_REDIRECT_HOST=${MT_SKIN_SERVER_OAUTH_REDIRECT_HOST}
      - MT_SKIN_SERVER_OAUTH_CONTENTDB_CLIENT_ID=${MT_SKIN_SERVER_OAUTH_CONTENTDB_CLIENT_ID}
      - MT_SKIN_SERVER_OAUTH_CONTENTDB_CLIENT_SECRET=${MT_SKIN_SERVER_OAUTH_CONTENTDB_CLIENT_SECRET}
      - MT_SKIN_SERVER_OAUTH_GITHUB_CLIENT_ID=${MT_SKIN_SERVER_OAUTH_GITHUB_CLIENT_ID}
      - MT_SKIN_SERVER_OAUTH_GITHUB_CLIENT_SECRET=${MT_SKIN_SERVER_OAUTH_GITHUB_CLIENT_SECRET}
      - MT_SKIN_SERVER_FRONTEND_DEV_MODE=true
      - MT_SKIN_SERVER_FRONTEND_URL=http://host.docker.internal:5173
    ports:
      - "8081:8081"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db

volumes:
  db:
