---
services:
  db:
    image: "postgres:16.2-alpine"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${MT_SKIN_SERVER_DB_USER}
      - POSTGRES_PASSWORD=${MT_SKIN_SERVER_DB_PASSWORD}
      - POSTGRES_DB=${MT_SKIN_SERVER_DB_NAME}
      - DATABASE_HOST=${MT_SKIN_SERVER_DB_HOST}
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data

  server_frontend:
    build: ./frontend
    expose:
      - "5173:5173"
    volumes:
      - type: bind
        source: ./frontend
        target: /frontend

  server:
    build: .
    environment:
      - MT_SKIN_SERVER_DB_USER=${MT_SKIN_SERVER_DB_USER}
      - MT_SKIN_SERVER_DB_PASSWORD=${MT_SKIN_SERVER_DB_PASSWORD}
      - MT_SKIN_SERVER_DB_NAME=${MT_SKIN_SERVER_DB_NAME}
      - MT_SKIN_SERVER_DB_HOST=${MT_SKIN_SERVER_DB_HOST}
      - MT_SKIN_SERVER_DB_PORT=${MT_SKIN_SERVER_DB_PORT}
      - MT_SKIN_SERVER_DATABASE_LOGGING=${MT_SKIN_SERVER_DATABASE_LOGGING}
      - MT_SKIN_SERVER_ENABLE_OPTIPNG=${MT_SKIN_SERVER_ENABLE_OPTIPNG}
      - MT_SKIN_SERVER_OAUTH_REDIRECT_HOST=${MT_SKIN_SERVER_OAUTH_REDIRECT_HOST}
      - MT_SKIN_SERVER_OAUTH_CONTENTDB_CLIENT_ID=${MT_SKIN_SERVER_OAUTH_CONTENTDB_CLIENT_ID}
      - MT_SKIN_SERVER_OAUTH_CONTENTDB_CLIENT_SECRET=${MT_SKIN_SERVER_OAUTH_CONTENTDB_CLIENT_SECRET}
      - MT_SKIN_SERVER_OAUTH_GITHUB_CLIENT_ID=${MT_SKIN_SERVER_OAUTH_GITHUB_CLIENT_ID}
      - MT_SKIN_SERVER_OAUTH_GITHUB_CLIENT_SECRET=${MT_SKIN_SERVER_OAUTH_GITHUB_CLIENT_SECRET}
      - MT_SKIN_SERVER_FRONTEND_DEV_MODE=true
      - MT_SKIN_SERVER_FRONTEND_URL=http://server_frontend:5173
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db:
