---
version: "3"
services:
  db:
    image: "postgres:14.1"
    restart: always
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data

  server:
    image: "ghcr.io/afcms/minetest-skin-server:master"
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db:
