---
version: "3"
services:
  db:
    image: "postgres:14.1"
    restart: always
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data

  server:
    build: .
    depends_on:
      - db

volumes:
  db:
