---
name: Linting

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  ESLint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "lts/iron"

      - name: Install dependencies
        run: npm install --include=dev # TODO: replace with npm ci

      - name: Lint with ESLint
        run: npm run lint

  GolangCI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: false

      - name: Lint with GolangCI
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
