---
name: Linting

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  ESLint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Enable PNPM
        run: corepack enable pnpm

      - name: Install dependencies
        run: cd $GITHUB_WORKSPACE/frontend && pnpm install --frozen-lockfile

      - name: Lint with ESLint
        run: cd $GITHUB_WORKSPACE/frontend && pnpm run lint

  GolangCI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: false

      - name: Lint with GolangCI
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
