---
name: Linting

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: github/super-linter@v4.10.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          VALIDATE_EDITORCONFIG: false
          VALIDATE_GO: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_ENV: false
          LINTER_RULES_PATH: /
          CSS_FILE_NAME: /frontend/stylelint.config.js
