---
name: Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - uses: actions/checkout@v3

      - name: Create Env File
        run: |
          cp exemple.env .env

      - name: Docker Compose Action
        uses: isbang/compose-action@v1.4.1

      - name: Run Newman
        run: |
          newman run ./postman/Minetest Skin Server_30e29402-3ae4-4cad-ba2e-150af06d3912.json -r htmlextra --reporter-htmlextra-export ./postman/report.html

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: ./postman/report.html
